Cleaned contract and testing, updated readme, decouple verify
ambhinav/HabitChain pull request #24
Opened 2022-04-08 08:30 UTC by Raihan9797

Remove unecessary commented out code from contract and test file
Update readme to install and run our code
decouple verify() into a check_user_list(), and verify().

2022-04-08 09:29 UTC, ambhinav requested changes

2022-04-08 09:29 UTC, ambhinav commented on test/test_habit.js
> +        console.log('user 1 checklist')
change to event check

2022-04-08 09:29 UTC, ambhinav commented on test/test_habit.js
> +        console.log('user 2 checklist')
change to event check

2022-04-08 13:09 UTC, Raihan9797 commented
Replace console.log with emit events in testing
Implemented transfer to main pool when all users lose a habit challenge
Contract owner can withdraw() from the main_pool
Implemented testing for these questions

2022-04-08 13:13 UTC, dragontho approved these changes

2022-04-09 03:40 UTC, ambhinav approved these changes
LGTM

2022-04-09 03:42 UTC, merged